# Site settings
title: Bit Byte Bit
subtitle: 
email: steveybrown@gmail.com
description: We craft beautiful experiences for you and your users.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://andrewbanchich.gitlab.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Belfast
state: TN
zip_code: 55555
country: United Kingdom
phone: (+44) 7522608535

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0 # deafult 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/u/isteveybrown
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/steveybrown
pinterest_url:
slack_url:
twitter_url: https://twitter.com/isteveybrown

# Build settings
markdown: kramdown
